Repository scalyr/scalyr-agent-2, pull requests merged in 2020-02, with the labels that each got.

#380 Log raw uncompressed request body in the Scalyr HTTP client debug log
  scalyr_agent/scalyr_client.py
  scalyr_agent/test_base.py
  scalyr_agent/tests/scalyr_client_test.py
  scalyr_agent/tests/scalyr_logging_test.py
  scalyr_agent/tests/test_util_test.py
Labels: tests: unit tests

#388 Add document which describes agent architecture and core code abstraction
  README.md
  docs/architecture.md
Labels: documentation

#392 Fix a couple of small Python 2 and 3 compatibility issues
  scalyr_agent/scalyr_client.py
  scalyr_agent/tests/configuration_test.py
  scalyr_agent/util.py
Labels: python 2 and 3 compatibility

#391 Test a codecov reporting change
  codecov.yml
Labels: service: codecov

#396 Move Python 2.6 unit tests to tox, Circle CI config clean up
  .circleci/config.yml
  conftest.py
  dev-requirements.txt
  lint-requirements.txt
  py26-unit-tests-requirements.txt
  scalyr_agent/all_tests.py
  scalyr_agent/json_lib/tests/encode_decode_test.py
  scalyr_agent/tests/configuration_k8s_test.py
  scalyr_agent/tests/log_processing_test.py
  tox.ini
Labels: service: circle ci, tests: unit tests

#397 Email us weekly Circle CI credit usage reports
  .circleci/config.yml
  scripts/circleci_usage_data.py
  tox.ini
Labels: service: circle ci

#394 Convert server response to text before python3.5 json.loads.
  scalyr_agent/scalyr_client.py
  scalyr_agent/tests/util/__init__.py
  scalyr_agent/tests/util/json_util_test.py
  scalyr_agent/tests/util/util_test.py
  scalyr_agent/util.py
Labels: python 2 and 3 compatibility

#403 Don't cache .tox directory
  .circleci/config.yml
Labels: service: circle ci

#400 Enable flake8 lint check for scalyr_agent/builtin_monitors/ directory
  dev-requirements.txt
  lint-configs/python/.flake8
  scalyr_agent/builtin_monitors/apache_monitor.py
  scalyr_agent/builtin_monitors/docker_monitor.py
  scalyr_agent/builtin_monitors/garbage_monitor.py
  scalyr_agent/builtin_monitors/journald_monitor.py
  scalyr_agent/builtin_monitors/kubernetes_events_monitor.py
  scalyr_agent/builtin_monitors/kubernetes_monitor.py
  scalyr_agent/builtin_monitors/linux_process_metrics.py
  scalyr_agent/builtin_monitors/mysql_monitor.py
  scalyr_agent/builtin_monitors/nginx_monitor.py
  scalyr_agent/builtin_monitors/postgres_monitor.py
  scalyr_agent/builtin_monitors/redis_monitor.py
  scalyr_agent/builtin_monitors/syslog_monitor.py
  scalyr_agent/builtin_monitors/tests/kubernetes_monitor_test.py
  scalyr_agent/builtin_monitors/tests/mysql_monitor_test.py
  scalyr_agent/builtin_monitors/tomcat_monitor.py
  scalyr_agent/builtin_monitors/url_monitor.py
  scalyr_agent/builtin_monitors/windows_event_log_monitor.py
  scalyr_agent/builtin_monitors/windows_process_metrics.py
  scalyr_agent/builtin_monitors/windows_system_metrics.py
  scalyr_agent/tests/configuration_docker_test.py
Labels: lint: flake8, tests: lint checks

#416 Send Circle CI usage reports to the new mailing list
  .circleci/config.yml
Labels: service: circle ci

#408 Improve response debug logging in the copying manager
  scalyr_agent/copying_manager.py
  scalyr_agent/tests/copying_manager_test.py
Labels: code: logging

#409 Fix metric types for "app.disk.requests" metrics
  scalyr_agent/builtin_monitors/linux_process_metrics.py
  scalyr_agent/scalyr_monitor.py
  scalyr_agent/tests/linux_process_metrics_test.py
Labels: code: monitors, monitors: linux process metrics

#412 Delete "__pycache__" directories in the package pre install and post remove scripts
  build_package.py
Labels: packaging

#414 Update pre-commit configuration so it matches tox lint configuration
  .pre-commit-config.yaml
  README.md
Labels: development environment

#418 Small pre-commit config fixes and improvements
  .circleci/modernize/modernize.py
  .pre-commit-config.yaml
  lint-configs/python/mypy.ini
  tox.ini
Labels: git: pre commit hook

#411 Continuous Tracking of Agent Resource Utilization and Performance
  .circleci/config.yml
  .circleci/coverage_report.py
  .circleci/docker_unified_smoke_unit/smoketest/smoketest.py
  .circleci/modernize/custom_fixers/fix_struct_unicode.py
  .circleci/modernize/modernize.py
  .pre-commit-config.yaml
  README.md
  benchmarks/README.md
  benchmarks/configs/agent.d/server.json
  benchmarks/configs/agent_no_monitored_logs.json
  benchmarks/configs/agent_no_monitored_logs_no_monitors.json
  benchmarks/configs/agent_single_50mb_access_log_file.json
  benchmarks/configs/agent_single_growing_log_file.json
  benchmarks/scripts/common.sh
  benchmarks/scripts/requirements.txt
  benchmarks/scripts/send-log-level-counts-to-codespeed.sh
  benchmarks/scripts/send_usage_data_to_codespeed.py
  benchmarks/scripts/send_value_to_codespeed.py
  benchmarks/scripts/start-agent-and-capture-metrics.sh
  benchmarks/scripts/utils.py
  benchmarks/scripts/write-random-lines.sh
  lint-configs/python/mypy.ini
  py26-unit-tests-requirements.txt
  tox.ini
Labels: service: circle ci, tests: performance tracking

#420 Performance tracking script fixes and improvements
  .circleci/config.yml
  benchmarks/README.md
  benchmarks/scripts/requirements.txt
  benchmarks/scripts/send_usage_data_to_codespeed.py
  benchmarks/scripts/utils.py
  scalyr_agent/builtin_monitors/linux_process_metrics.py
  scalyr_agent/builtin_monitors/tests/docker_monitor_test.py
Labels: continuous benchmarking

#426 Fix typos in benchmarks/README.md
  benchmarks/README.md
Labels: documentation

#419 Cherry pick performance tracking changes into release branch
  .circleci/config.yml
  benchmarks/README.md
  benchmarks/configs/agent.d/server.json
  benchmarks/configs/agent_no_monitored_logs.json
  benchmarks/configs/agent_no_monitored_logs_no_monitors.json
  benchmarks/configs/agent_single_50mb_access_log_file.json
  benchmarks/configs/agent_single_growing_log_file.json
  benchmarks/scripts/common.sh
  benchmarks/scripts/requirements.txt
  benchmarks/scripts/send-log-level-counts-to-codespeed.sh
  benchmarks/scripts/send_usage_data_to_codespeed.py
  benchmarks/scripts/send_value_to_codespeed.py
  benchmarks/scripts/start-agent-and-capture-metrics.sh
  benchmarks/scripts/utils.py
  benchmarks/scripts/write-random-lines.sh
Labels: continuous benchmarking

#422 fix struct.pack|unpack wrapper for python < 2.7.7
  scalyr_agent/builtin_monitors/syslog_monitor.py
  scalyr_agent/compat.py
  scalyr_agent/json_lib/serializer.py
  scalyr_agent/monitor_utils/server_processors.py
  scalyr_agent/monitor_utils/tests/server_processors_test.py
  scalyr_agent/platform_windows.py
  scalyr_agent/test_util.py
  scalyr_agent/tests/util/util_test.py
  scalyr_agent/util.py
Labels: python 2 and 3 compatibility, python2/3

#429 Fix six import in config_main.py
  scalyr_agent/config_main.py
Labels: python 2 and 3 compatibility

#425 Improve error handling in Circle CI usage data script
  scripts/circleci_usage_data.py
Labels: service: circle ci

#432 Fix Python 3 related errors in the tcollectors
  scalyr_agent/third_party/tcollector/tcollector.py
Labels: python 2 and 3 compatibility

#430 pylint plugin for checking / enforcing ordering of bundled third party module imports
  lint-configs/python/mypy.ini
  pylint_plugins/__init__.py
  pylint_plugins/bundled_imports_checker.py
  tox.ini
Labels: tests: lint checks

#436 Fix string issue when building Windows package
  build_package.py
  scalyr_agent/tests/util/util_test.py
  scalyr_agent/util.py
Labels: python 2 and 3 compatibility
